#!/usr/bin/env python3
import argparse, json, pymysql
def main():
    p=argparse.ArgumentParser(); p.add_argument("--db-host",default="127.0.0.1"); p.add_argument("--db-port",type=int,default=3306); p.add_argument("--db-user",required=True); p.add_argument("--db-pass",required=True); p.add_argument("--db-name",required=True); p.add_argument("--profile-id",required=True); p.add_argument("--dt",required=True); p.add_argument("--run-id",default=""); p.add_argument("--scenario-name",default=""); a=p.parse_args()
    conn=pymysql.connect(host=a.db_host,port=a.db_port,user=a.db_user,password=a.db_pass,database=a.db_name,charset="utf8mb4",autocommit=False,cursorclass=pymysql.cursors.DictCursor)
    try:
        with conn.cursor() as cur:
            cur.execute("""SELECT r.*, s.integrity_score,s.completeness_score,s.timeliness_score,s.consistency_score,s.availability_score,s.dominant_semantic_risk,s.delta_source_type,s.fallback_used,u.overall_risk_score,u.final_risk_level,a.recommended_action,a.priority,m.direct_completeness_delta,m.direct_timeliness_delta,m.direct_availability_delta FROM r_reliability_analysis_result_day r JOIN semantic_interpretation_day s ON r.profile_id=s.profile_id AND r.dt=s.dt AND r.run_id=s.run_id JOIN unified_reliability_score_day u ON r.profile_id=u.profile_id AND r.dt=u.dt AND r.run_id=u.run_id JOIN action_recommendation_day a ON r.profile_id=a.profile_id AND r.dt=a.dt AND r.run_id=a.run_id LEFT JOIN measurement_realism_day m ON r.profile_id=m.profile_id AND r.dt=m.dt AND r.run_id=m.run_id WHERE r.profile_id=%s AND r.dt=%s AND r.run_id=%s LIMIT 1""",(a.profile_id,a.dt,a.run_id or ""))
            row=cur.fetchone()
            if not row: raise RuntimeError("missing architecture rows for ML feature snapshot")
            fj=json.dumps({k:str(v) if v is not None else None for k,v in row.items()},ensure_ascii=False)
            cur.execute("DELETE FROM ml_feature_snapshot_day WHERE profile_id=%s AND dt=%s AND run_id=%s",(a.profile_id,a.dt,a.run_id or ""))
            cur.execute("""INSERT INTO ml_feature_snapshot_day (profile_id,dt,run_id,scenario_name,drift_score,propagation_score,amplification_score,distortion_score,baseline_delta,correlation_score,integrity_score,completeness_score,timeliness_score,consistency_score,availability_score,overall_risk_score,final_risk_level,dominant_semantic_risk,recommended_action,priority,delta_source_type,fallback_used,direct_completeness_delta,direct_timeliness_delta,direct_availability_delta,label_risk_family,label_action,feature_json) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""",(a.profile_id,a.dt,a.run_id or "",a.scenario_name or row.get("scenario_name") or "",row.get("drift_score") or 0,row.get("propagation_score") or 0,row.get("amplification_score") or 0,row.get("distortion_score") or 0,row.get("baseline_delta") or 0,row.get("correlation_score") or 0,row.get("integrity_score") or 0,row.get("completeness_score") or 0,row.get("timeliness_score") or 0,row.get("consistency_score") or 0,row.get("availability_score") or 0,row.get("overall_risk_score") or 0,row.get("final_risk_level") or "UNKNOWN",row.get("dominant_semantic_risk") or "Unknown",row.get("recommended_action") or "manual investigation",row.get("priority") or "P3",row.get("delta_source_type") or "UNKNOWN",row.get("fallback_used") or 0,row.get("direct_completeness_delta") or 0,row.get("direct_timeliness_delta") or 0,row.get("direct_availability_delta") or 0,row.get("expected_risk_family") or "unknown",row.get("recommended_action") or "manual investigation",fj))
        conn.commit()
    finally: conn.close()
    print(f"[ML_FEATURE] built ml_feature_snapshot_day profile_id={a.profile_id} dt={a.dt} run_id={a.run_id}")
if __name__=="__main__": main()
