#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path.cwd()
GEN = ROOT / "simulator" / "weblog_sim" / "core" / "generator.py"

MARKER = "# v0.4 no_data explicit source marker"

METHOD = r'''
    # v0.4 no_data explicit source marker
    def _render_no_data_marker_line(self, dt: datetime, site_key: str) -> str:
        """Render an explicit source-level no_data marker line.

        When suppress_input=1, normal events are intentionally dropped, so there
        may be no user event to carry drift=on / affected=1 / anomaly_type=no_data.
        This marker is generated by simulator core, not by source-file rewrite,
        and lets downstream validation distinguish "true source collapse" from
        "no anomaly metadata".
        """
        import os

        meta: LogFormatMeta = self.meta_store.get(site_key)
        exo = self._exo(dt)
        scenario_id = os.environ.get("SOURCE_SCENARIO_ID", "source_no_data")
        run_id = os.environ.get("SOURCE_RUN_ID", "")
        experiment_id = os.environ.get("EXPERIMENT_ID", "")
        exo_state_id = f"exo_{dt.strftime('%Y%m%d_%H')}"
        contract_id = f"contract_{scenario_id}"

        kv = (
            f"cc=NA; al=na; device=system; "
            f"pcid=no_data_marker; sid=no_data_{dt.strftime('%Y%m%d%H%M')}; uid=; "
            f"evt=source_no_data_marker; page_type=source_control; "
            f"latency_ms=0; http_status=204; "
            f"schema_version={getattr(exo, 'schema_version', 'v0.4-source-anomaly-contract')}; "
            f"scenario_id={scenario_id}; scenario_name={scenario_id}; "
            f"domain=web; source_layer=behavior; anomaly_type=no_data; "
            f"drift=on; affected=1; exo_state_id={exo_state_id}; "
            f"anomaly_contract_id={contract_id}; experiment_id={experiment_id}; run_id={run_id}; "
            f"weather_type={getattr(exo, 'weather_type', 'clear')}; "
            f"campaign_flag={getattr(exo, 'campaign_flag', 'none')}; "
            f"system_flag={getattr(exo, 'system_flag', 'normal')}; "
            f"volume_multiplier={getattr(exo, 'volume_multiplier', 1.0)}; "
            f"conversion_multiplier={getattr(exo, 'conversion_multiplier', 1.0)}; "
            f"latency_shift_ms={getattr(exo, 'latency_shift_ms', 0)}; "
            f"drop_probability={getattr(exo, 'drop_probability', 0.0)}; "
            f"timeout_multiplier={getattr(exo, 'timeout_multiplier', 1.0)}; "
            f"retry_multiplier={getattr(exo, 'retry_multiplier', 1.0)}; "
            f"duplicate_multiplier={getattr(exo, 'duplicate_multiplier', 1.0)}; "
            f"event_time_skew_ms={getattr(exo, 'event_time_skew_ms', 0)}; "
            f"suppress_input=1; "
            f"schema_flag={getattr(exo, 'schema_flag', 'normal')}; "
            f"identity_flag={getattr(exo, 'identity_flag', 'normal')}; "
            f"pcid_stability={getattr(exo, 'pcid_stability', 'stable')}; "
            f"session_stability={getattr(exo, 'session_stability', 'stable')}; "
            f"customer_id_stability={getattr(exo, 'customer_id_stability', 'stable')}; "
            f"traffic_actor=system; bot_flag=0; user_agent_flag=marker; ip_concentration_flag=normal; "
            f"recovery_flag=none; backlog_flush=0; transaction_delay_ms=0; event_ingestion_delay_ms=0; "
            f"privacy_flag=normal; pii_detected=0; sensitive_field_flag=none; masking_status=not_applicable; "
            f"financial_product=none; funnel_stage=none; state_transition=none; "
            f"expected_state=none; actual_state=none; reconciliation_flag=source_no_data_marker; "
            f"exo_source=exogenous_timeline_v1;"
        )
        ts = apache_time(dt.astimezone(meta.tz))
        return meta.template.format(
            ip="0.0.0.0",
            ts=ts,
            method="GET",
            path="/__source_anomaly__/no_data_marker.do",
            httpv=meta.http_version,
            status=204,
            bytes=0,
            ref="-",
            ua="source-no-data-marker/1.0",
            kv=kv,
        )

'''

BLOCK = r'''            # v0.4 no_data explicit source marker
            # Emit one marker per minute while suppress_input=1. Normal user events
            # are not generated in this window, but the source contract still needs
            # explicit drift/affected/anomaly_type metadata for audit and downstream
            # validation. This is generated inside simulator core, not by rewriting
            # the source file after generation.
            if getattr(exo, "suppress_input", False):
                marker_key = dt.strftime("%Y-%m-%dT%H:%M")
                if not hasattr(self, "_no_data_marker_keys"):
                    self._no_data_marker_keys = set()
                if marker_key not in self._no_data_marker_keys:
                    self._no_data_marker_keys.add(marker_key)
                    yield self._render_no_data_marker_line(dt, site_key=site_key)
                dt += timedelta(seconds=1)
                continue

'''


def main() -> None:
    if not GEN.exists():
        raise SystemExit(f"generator.py not found: {GEN}")
    text = GEN.read_text(encoding="utf-8")
    if MARKER in text:
        print(f"[OK] no_data marker patch already present: {GEN}")
        return
    backup = GEN.with_suffix(".py.bak_no_data_marker")
    backup.write_text(text, encoding="utf-8")

    if "    def generate(" not in text:
        raise SystemExit("Could not find WeblogGenerator.generate method")
    text = text.replace("    def generate(", METHOD + "    def generate(", 1)

    target = "        while dt <= end_dt:\n            exo = self._exo(dt)\n"
    if target not in text:
        raise SystemExit("Could not find generate loop anchor: while dt <= end_dt / exo assignment")
    text = text.replace(target, target + BLOCK, 1)

    GEN.write_text(text, encoding="utf-8")
    print(f"[OK] patched {GEN}")
    print(f"[INFO] backup {backup}")


if __name__ == "__main__":
    main()
