suppressPackageStartupMessages({ library(jsonlite); library(stats) })
args <- commandArgs(trailingOnly=TRUE)
arg <- function(name, default=NULL) { key <- paste0("--", name); i <- match(key, args); if (!is.na(i) && i < length(args)) return(args[[i+1]]); default }
cfg <- list(db_host=arg("db-host","127.0.0.1"), db_port=arg("db-port","3306"), db_user=arg("db-user"), db_pass=arg("db-pass"), db_name=arg("db-name"), profile_id=arg("profile-id"), dt=arg("dt", arg("dt-from")), run_id=arg("run-id",""), scenario_name=arg("scenario-name",""), baseline_dt=arg("baseline-dt", arg("dt", arg("dt-from"))), expected_risk_family=arg("expected-risk-family","unknown"))
mysql_args <- function(extra=c()) c("-h", cfg$db_host, "-P", cfg$db_port, "-u", cfg$db_user, paste0("-p", cfg$db_pass), cfg$db_name, extra)
sql_escape <- function(x){ x <- as.character(x); x <- gsub("\\\\","\\\\\\\\",x); x <- gsub("'","''",x); paste0("'",x,"'") }
qi <- function(x) paste0("`", gsub("`","``", as.character(x)), "`")
query_df <- function(sql){ tf <- tempfile(fileext=".sql"); writeLines(sql, tf, useBytes=TRUE); out <- tryCatch(system2("mysql", mysql_args(c("-N","-B")), stdin=tf, stdout=TRUE, stderr=TRUE), error=function(e) structure(character(), status=1, stderr=conditionMessage(e))); status <- attr(out,"status"); if(!is.null(status) && status!=0) stop(paste(c("mysql query failed:",out), collapse="\n")); if(length(out)==0) return(data.frame()); read.delim(text=paste(out,collapse="\n"), header=FALSE, sep="\t", stringsAsFactors=FALSE, quote="", check.names=FALSE) }
exec_sql <- function(sql){ tf <- tempfile(fileext=".sql"); writeLines(sql, tf, useBytes=TRUE); out <- tryCatch(system2("mysql", mysql_args(), stdin=tf, stdout=TRUE, stderr=TRUE), error=function(e) structure(character(), status=1, stderr=conditionMessage(e))); status <- attr(out,"status"); if(!is.null(status)&&status!=0) stop(paste(c("mysql exec failed:",out), collapse="\n")); invisible(TRUE) }
scalar <- function(sql, default=0){ d <- query_df(sql); if(nrow(d)==0 || ncol(d)==0) return(default); v <- d[1,1]; if(is.na(v)||v=="NULL") return(default); v }
table_exists <- function(t) as.integer(scalar(paste0("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=", sql_escape(t), ";"),0)) > 0
col_exists <- function(t,c){ if(!table_exists(t)) return(FALSE); as.integer(scalar(paste0("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=", sql_escape(t), " AND column_name=", sql_escape(c), ";"),0)) > 0 }
first_col <- function(t, cs){ for(c in cs) if(col_exists(t,c)) return(c); NA_character_ }
nz <- function(x,d=0){ if(length(x)==0||is.null(x)||is.na(x)||x=="NULL") return(d); x <- suppressWarnings(as.numeric(x)); if(!is.finite(x)) return(d); x }
clip01 <- function(x) max(0, min(1, nz(x)))
safe_ratio <- function(a,b){ a<-nz(a); b<-nz(b); if(abs(b)<1e-9) return(ifelse(abs(a)<1e-9,0,a)); a/b }
status_by_score <- function(x) ifelse(nz(x)>=0.6,"FAIL",ifelse(nz(x)>=0.2,"WARN","PASS"))
risk_level <- function(score){ s<-nz(score); if(s>=0.80) return("CRITICAL"); if(s>=0.60) return("HIGH"); if(s>=0.30) return("MEDIUM"); if(s>0) return("LOW"); "STABLE" }
sql_num <- function(x){ x<-nz(x); if(!is.finite(x)) x<-0; as.character(x) }
query_table <- function(t,d=cfg$dt,run_id=cfg$run_id,limit=NULL,date_col="dt"){ if(!table_exists(t)) return(data.frame()); w<-c("1=1"); if(col_exists(t,"profile_id")) w<-c(w,paste0("profile_id=",sql_escape(cfg$profile_id))); if(col_exists(t,date_col)) w<-c(w,paste0(qi(date_col),"=",sql_escape(d))); if(col_exists(t,"run_id") && run_id!="") w<-c(w,paste0("run_id=",sql_escape(run_id))); sql<-paste0("SELECT * FROM ",qi(t)," WHERE ",paste(w,collapse=" AND ")); if(!is.null(limit)) sql<-paste0(sql," LIMIT ",as.integer(limit)); sql<-paste0(sql,";"); dfr<-query_df(sql); if(nrow(dfr)>0){ cols<-query_df(paste0("SHOW COLUMNS FROM ",qi(t),";")); if(nrow(cols)>0 && ncol(dfr)==nrow(cols)) names(dfr)<-cols[,1]}; dfr}
read_one <- function(t,d=cfg$dt,run_id=cfg$run_id,date_col="dt") query_table(t,d,run_id,1,date_col)
val <- function(df,c,d=0){ if(nrow(df)==0 || !(c %in% names(df))) return(d); nz(df[[c]][[1]],d) }
integrated_score_from_phase2 <- function(d=cfg$dt, run_id=cfg$run_id){ for(t in c("scenario_validation_report_v1","integrated_risk_score_day_v04","data_risk_score_day_v3")){ if(!table_exists(t)) next; sc<-first_col(t,c("integrated_risk_score","actual_score","overall_risk_score","risk_score","score")); dc<-first_col(t,c("target_date","dt")); if(is.na(sc)||is.na(dc)) next; w<-c(paste0(qi(dc),"=",sql_escape(d))); if(col_exists(t,"profile_id")) w<-c(w,paste0("profile_id=",sql_escape(cfg$profile_id))); if(col_exists(t,"run_id") && run_id!="") w<-c(w,paste0("run_id=",sql_escape(run_id))); v<-scalar(paste0("SELECT COALESCE(",qi(sc),",0) FROM ",qi(t)," WHERE ",paste(w,collapse=" AND ")," LIMIT 1;"),NA); if(!is.na(suppressWarnings(as.numeric(v)))) return(nz(v))}; NA_real_ }
dominant_signal_from_phase2 <- function(){ for(t in c("scenario_validation_report_v1","scenario_propagation_summary_v1","integrated_risk_score_day_v04","data_risk_score_day_v3")){ if(!table_exists(t)) next; sc<-first_col(t,c("strongest_signal","actual_signal","dominant_signal","root_cause_signal","dominant_risk_type","risk_type")); dc<-first_col(t,c("target_date","dt")); if(is.na(sc)||is.na(dc)) next; w<-c(paste0(qi(dc),"=",sql_escape(cfg$dt))); if(col_exists(t,"profile_id")) w<-c(w,paste0("profile_id=",sql_escape(cfg$profile_id))); if(col_exists(t,"run_id") && cfg$run_id!="") w<-c(w,paste0("run_id=",sql_escape(cfg$run_id))); v<-scalar(paste0("SELECT COALESCE(",qi(sc),",'') FROM ",qi(t)," WHERE ",paste(w,collapse=" AND ")," LIMIT 1;"),""); if(!is.null(v)&&!is.na(v)&&v!=""&&v!="NULL") return(as.character(v))}; "" }
signal_to_family <- function(signal){ s<-tolower(as.character(signal)); if(s==""||is.na(s)) return("unknown"); if(grepl("comple|missing|partial|drop|no_data",s)) return("completeness"); if(grepl("schema|validation|contract|integrity",s)) return("schema_validation"); if(grepl("latency|lag|delay|freshness|performance",s)) return("latency_performance"); if(grepl("availability|timeout|retry|resource|saturation",s)) return("availability"); "unknown" }
risk_family_to_layer <- function(family){ switch(family, "completeness"="batch", "schema_validation"="batch", "identity_mapping"="batch", "latency_performance"="stream", "availability"="operational", "low"="", "") }
