-- v0.5 Phase 2: Transaction / State Canonicalization
-- SQL role: deterministic persistence and canonical/mapping state only.

CREATE TABLE IF NOT EXISTS v05_transaction_log_raw (
  raw_transaction_id BIGINT NOT NULL AUTO_INCREMENT,
  profile_id VARCHAR(128) NOT NULL,
  target_date DATE NOT NULL,
  run_id BIGINT DEFAULT NULL,
  source_gen_run_id BIGINT DEFAULT NULL,
  source_file_path VARCHAR(1024) NOT NULL,
  source_row_number BIGINT NOT NULL,
  event_time DATETIME NOT NULL,
  journey_id VARCHAR(128) DEFAULT NULL,
  transaction_event VARCHAR(128) NOT NULL,
  customer_id VARCHAR(128) DEFAULT NULL,
  product_id VARCHAR(128) DEFAULT NULL,
  cart_id VARCHAR(128) DEFAULT NULL,
  coupon_id VARCHAR(128) DEFAULT NULL,
  order_id VARCHAR(128) DEFAULT NULL,
  payment_id VARCHAR(128) DEFAULT NULL,
  delivery_id VARCHAR(128) DEFAULT NULL,
  amount DECIMAL(18,2) DEFAULT NULL,
  currency VARCHAR(16) DEFAULT NULL,
  source_system VARCHAR(128) DEFAULT NULL,
  behavior_anchor_stage VARCHAR(128) DEFAULT NULL,
  behavior_anchor_offset_sec INT DEFAULT NULL,
  transaction_delay_ms INT DEFAULT NULL,
  anomaly_flag TINYINT(1) NOT NULL DEFAULT 0,
  payload_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(payload_json)),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (raw_transaction_id),
  KEY idx_v05_tx_raw_scope (profile_id, target_date, run_id, source_gen_run_id),
  KEY idx_v05_tx_raw_journey (journey_id),
  KEY idx_v05_tx_raw_order_payment (order_id, payment_id),
  KEY idx_v05_tx_raw_time (event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v05_state_log_raw (
  raw_state_id BIGINT NOT NULL AUTO_INCREMENT,
  profile_id VARCHAR(128) NOT NULL,
  target_date DATE NOT NULL,
  run_id BIGINT DEFAULT NULL,
  source_gen_run_id BIGINT DEFAULT NULL,
  source_file_path VARCHAR(1024) NOT NULL,
  source_row_number BIGINT NOT NULL,
  event_time DATETIME NOT NULL,
  journey_id VARCHAR(128) DEFAULT NULL,
  state_event VARCHAR(128) NOT NULL,
  customer_id VARCHAR(128) DEFAULT NULL,
  order_id VARCHAR(128) DEFAULT NULL,
  payment_id VARCHAR(128) DEFAULT NULL,
  delivery_id VARCHAR(128) DEFAULT NULL,
  coupon_id VARCHAR(128) DEFAULT NULL,
  order_amount DECIMAL(18,2) DEFAULT NULL,
  expected_amount DECIMAL(18,2) DEFAULT NULL,
  state_status VARCHAR(128) DEFAULT NULL,
  source_system VARCHAR(128) DEFAULT NULL,
  behavior_anchor_stage VARCHAR(128) DEFAULT NULL,
  behavior_anchor_offset_sec INT DEFAULT NULL,
  state_transition_delay_ms INT DEFAULT NULL,
  anomaly_flag TINYINT(1) NOT NULL DEFAULT 0,
  payload_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(payload_json)),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (raw_state_id),
  KEY idx_v05_state_raw_scope (profile_id, target_date, run_id, source_gen_run_id),
  KEY idx_v05_state_raw_journey (journey_id),
  KEY idx_v05_state_raw_order_payment (order_id, payment_id),
  KEY idx_v05_state_raw_time (event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS canonical_behavior_events (
  canonical_behavior_event_id BIGINT NOT NULL AUTO_INCREMENT,
  canonical_event_id BIGINT DEFAULT NULL,
  run_id BIGINT NOT NULL,
  profile_id VARCHAR(128) NOT NULL,
  source_gen_run_id BIGINT DEFAULT NULL,
  target_date DATE NOT NULL,
  event_time DATETIME NOT NULL,
  event_type VARCHAR(64) DEFAULT NULL,
  uid VARCHAR(128) DEFAULT NULL,
  pcid VARCHAR(128) DEFAULT NULL,
  session_id VARCHAR(128) DEFAULT NULL,
  journey_id VARCHAR(128) DEFAULT NULL,
  journey_stage VARCHAR(128) DEFAULT NULL,
  product_id VARCHAR(128) DEFAULT NULL,
  cart_id VARCHAR(128) DEFAULT NULL,
  coupon_id VARCHAR(128) DEFAULT NULL,
  order_id VARCHAR(128) DEFAULT NULL,
  payment_id VARCHAR(128) DEFAULT NULL,
  delivery_id VARCHAR(128) DEFAULT NULL,
  customer_segment VARCHAR(64) DEFAULT NULL,
  device_type VARCHAR(64) DEFAULT NULL,
  app_platform VARCHAR(64) DEFAULT NULL,
  app_version VARCHAR(64) DEFAULT NULL,
  sdk_version VARCHAR(64) DEFAULT NULL,
  page_type VARCHAR(128) DEFAULT NULL,
  funnel_stage VARCHAR(128) DEFAULT NULL,
  amount_expected DECIMAL(18,2) DEFAULT NULL,
  amount_actual DECIMAL(18,2) DEFAULT NULL,
  scenario_id VARCHAR(128) DEFAULT NULL,
  anomaly_type VARCHAR(128) DEFAULT NULL,
  reconciliation_flag VARCHAR(128) DEFAULT NULL,
  canonical_payload_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(canonical_payload_json)),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (canonical_behavior_event_id),
  KEY idx_v05_cb_scope (profile_id, target_date, run_id, source_gen_run_id),
  KEY idx_v05_cb_obs_meta (profile_id, source_gen_run_id, app_platform, app_version, sdk_version),
  KEY idx_v05_cb_journey (journey_id),
  KEY idx_v05_cb_order_payment (order_id, payment_id),
  KEY idx_v05_cb_stage_time (journey_stage, event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS canonical_transaction_events (
  canonical_transaction_event_id BIGINT NOT NULL AUTO_INCREMENT,
  raw_transaction_id BIGINT DEFAULT NULL,
  run_id BIGINT NOT NULL,
  profile_id VARCHAR(128) NOT NULL,
  source_gen_run_id BIGINT DEFAULT NULL,
  target_date DATE NOT NULL,
  event_time DATETIME NOT NULL,
  journey_id VARCHAR(128) DEFAULT NULL,
  transaction_event VARCHAR(128) NOT NULL,
  transaction_type VARCHAR(128) DEFAULT NULL,
  customer_id VARCHAR(128) DEFAULT NULL,
  product_id VARCHAR(128) DEFAULT NULL,
  cart_id VARCHAR(128) DEFAULT NULL,
  coupon_id VARCHAR(128) DEFAULT NULL,
  order_id VARCHAR(128) DEFAULT NULL,
  payment_id VARCHAR(128) DEFAULT NULL,
  delivery_id VARCHAR(128) DEFAULT NULL,
  amount DECIMAL(18,2) DEFAULT NULL,
  currency VARCHAR(16) DEFAULT NULL,
  source_system VARCHAR(128) DEFAULT NULL,
  behavior_anchor_stage VARCHAR(128) DEFAULT NULL,
  transaction_delay_ms INT DEFAULT NULL,
  duplicate_key VARCHAR(512) DEFAULT NULL,
  anomaly_flag TINYINT(1) NOT NULL DEFAULT 0,
  canonical_payload_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(canonical_payload_json)),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (canonical_transaction_event_id),
  KEY idx_v05_ct_scope (profile_id, target_date, run_id, source_gen_run_id),
  KEY idx_v05_ct_journey (journey_id),
  KEY idx_v05_ct_order_payment (order_id, payment_id),
  KEY idx_v05_ct_event_time (transaction_event, event_time),
  KEY idx_v05_ct_dup_key (duplicate_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS canonical_state_events (
  canonical_state_event_id BIGINT NOT NULL AUTO_INCREMENT,
  raw_state_id BIGINT DEFAULT NULL,
  run_id BIGINT NOT NULL,
  profile_id VARCHAR(128) NOT NULL,
  source_gen_run_id BIGINT DEFAULT NULL,
  target_date DATE NOT NULL,
  event_time DATETIME NOT NULL,
  journey_id VARCHAR(128) DEFAULT NULL,
  state_event VARCHAR(128) NOT NULL,
  state_entity VARCHAR(128) DEFAULT NULL,
  state_status VARCHAR(128) DEFAULT NULL,
  customer_id VARCHAR(128) DEFAULT NULL,
  order_id VARCHAR(128) DEFAULT NULL,
  payment_id VARCHAR(128) DEFAULT NULL,
  delivery_id VARCHAR(128) DEFAULT NULL,
  coupon_id VARCHAR(128) DEFAULT NULL,
  order_amount DECIMAL(18,2) DEFAULT NULL,
  expected_amount DECIMAL(18,2) DEFAULT NULL,
  source_system VARCHAR(128) DEFAULT NULL,
  behavior_anchor_stage VARCHAR(128) DEFAULT NULL,
  state_transition_delay_ms INT DEFAULT NULL,
  duplicate_key VARCHAR(512) DEFAULT NULL,
  anomaly_flag TINYINT(1) NOT NULL DEFAULT 0,
  canonical_payload_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(canonical_payload_json)),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (canonical_state_event_id),
  KEY idx_v05_cs_scope (profile_id, target_date, run_id, source_gen_run_id),
  KEY idx_v05_cs_journey (journey_id),
  KEY idx_v05_cs_order_payment (order_id, payment_id),
  KEY idx_v05_cs_event_time (state_event, event_time),
  KEY idx_v05_cs_dup_key (duplicate_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS behavior_transaction_mapping (
  mapping_id BIGINT NOT NULL AUTO_INCREMENT,
  run_id BIGINT NOT NULL,
  profile_id VARCHAR(128) NOT NULL,
  source_gen_run_id BIGINT DEFAULT NULL,
  target_date DATE NOT NULL,
  journey_id VARCHAR(128) DEFAULT NULL,
  order_id VARCHAR(128) DEFAULT NULL,
  payment_id VARCHAR(128) DEFAULT NULL,
  canonical_behavior_event_id BIGINT DEFAULT NULL,
  canonical_transaction_event_id BIGINT DEFAULT NULL,
  behavior_stage VARCHAR(128) DEFAULT NULL,
  transaction_event VARCHAR(128) DEFAULT NULL,
  mapping_status VARCHAR(64) NOT NULL,
  orphan_flag TINYINT(1) NOT NULL DEFAULT 0,
  duplicate_flag TINYINT(1) NOT NULL DEFAULT 0,
  state_transition_flag VARCHAR(64) NOT NULL DEFAULT 'not_evaluated',
  time_gap_ms BIGINT DEFAULT NULL,
  mapping_key VARCHAR(512) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (mapping_id),
  KEY idx_v05_btm_scope (profile_id, target_date, run_id, source_gen_run_id),
  KEY idx_v05_btm_journey (journey_id),
  KEY idx_v05_btm_status (mapping_status),
  KEY idx_v05_btm_key (mapping_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS transaction_state_mapping (
  mapping_id BIGINT NOT NULL AUTO_INCREMENT,
  run_id BIGINT NOT NULL,
  profile_id VARCHAR(128) NOT NULL,
  source_gen_run_id BIGINT DEFAULT NULL,
  target_date DATE NOT NULL,
  journey_id VARCHAR(128) DEFAULT NULL,
  order_id VARCHAR(128) DEFAULT NULL,
  payment_id VARCHAR(128) DEFAULT NULL,
  delivery_id VARCHAR(128) DEFAULT NULL,
  canonical_transaction_event_id BIGINT DEFAULT NULL,
  canonical_state_event_id BIGINT DEFAULT NULL,
  transaction_event VARCHAR(128) DEFAULT NULL,
  state_event VARCHAR(128) DEFAULT NULL,
  mapping_status VARCHAR(64) NOT NULL,
  orphan_flag TINYINT(1) NOT NULL DEFAULT 0,
  duplicate_flag TINYINT(1) NOT NULL DEFAULT 0,
  state_transition_flag VARCHAR(64) NOT NULL DEFAULT 'unknown',
  time_gap_ms BIGINT DEFAULT NULL,
  mapping_key VARCHAR(512) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (mapping_id),
  KEY idx_v05_tsm_scope (profile_id, target_date, run_id, source_gen_run_id),
  KEY idx_v05_tsm_journey (journey_id),
  KEY idx_v05_tsm_status (mapping_status),
  KEY idx_v05_tsm_key (mapping_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
