-- v0.5 Runtime Evidence Interface
CREATE TABLE IF NOT EXISTS v05_runtime_evidence_day (
  evidence_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  profile_id VARCHAR(100) NOT NULL,
  target_date DATE NOT NULL,
  dt DATE NOT NULL,
  run_id BIGINT NOT NULL,
  source_gen_run_id BIGINT NULL,
  scenario_name VARCHAR(100) NOT NULL,
  batch_evidence_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  stream_evidence_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  operational_evidence_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  realism_evidence_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  runtime_evidence_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  batch_signal VARCHAR(200) NULL,
  stream_signal VARCHAR(200) NULL,
  operational_signal VARCHAR(200) NULL,
  realism_signal VARCHAR(200) NULL,
  dominant_runtime_signal VARCHAR(200) NULL,
  direct_completeness_delta DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  direct_timeliness_delta DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  direct_availability_delta DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  direct_integrity_delta DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  behavior_distortion_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  conversion_distortion_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  session_fragmentation_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  identity_anomaly_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  mapping_risk_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  batch_quality_risk_score DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  stream_duplicate_rate DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  stream_late_event_rate DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  stream_missing_event_rate DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  stream_ordering_violation_rate DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  stream_event_count BIGINT NOT NULL DEFAULT 0,
  operational_availability_score DECIMAL(14,6) NOT NULL DEFAULT 1.000000,
  operational_performance_score DECIMAL(14,6) NOT NULL DEFAULT 1.000000,
  operational_error_rate DECIMAL(14,6) NOT NULL DEFAULT 0.000000,
  batch_event_count BIGINT NOT NULL DEFAULT 0,
  canonical_event_count BIGINT NOT NULL DEFAULT 0,
  canonical_behavior_count BIGINT NOT NULL DEFAULT 0,
  canonical_transaction_count BIGINT NOT NULL DEFAULT 0,
  canonical_state_count BIGINT NOT NULL DEFAULT 0,
  evidence_level VARCHAR(50) NOT NULL DEFAULT 'low',
  evidence_status VARCHAR(50) NOT NULL DEFAULT 'completed',
  evidence_policy VARCHAR(100) NOT NULL DEFAULT 'v05_runtime_evidence_only',
  evidence_payload_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_v05_runtime_evidence_day (profile_id, target_date, run_id, scenario_name),
  KEY idx_v05_runtime_evidence_day_lookup (profile_id, target_date, scenario_name),
  KEY idx_v05_runtime_evidence_day_source_gen (source_gen_run_id),
  KEY idx_v05_runtime_evidence_day_level (evidence_level, runtime_evidence_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
