CREATE TABLE IF NOT EXISTS v05_batch_score_contribution_day (
  profile_id VARCHAR(128) NOT NULL,
  dt DATE NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT DEFAULT NULL,
  scenario_name VARCHAR(128) NOT NULL DEFAULT 'baseline',
  baseline_mode VARCHAR(64) DEFAULT 'temporal_baseline',
  baseline_window VARCHAR(32) DEFAULT '30d',
  score_family VARCHAR(128) NOT NULL,
  input_metric_scope VARCHAR(128) NOT NULL,
  input_metric_name VARCHAR(128) NOT NULL,
  current_value DOUBLE DEFAULT NULL,
  baseline_value DOUBLE DEFAULT NULL,
  delta_rate DOUBLE DEFAULT NULL,
  metric_risk_score DOUBLE DEFAULT 0,
  weight DOUBLE DEFAULT 1,
  contribution_score DOUBLE DEFAULT 0,
  contribution_reason VARCHAR(1024) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_v05_batch_score_contribution_scope (profile_id, dt, run_id, scenario_name),
  KEY idx_v05_batch_score_contribution_source_gen (profile_id, dt, source_gen_run_id, scenario_name),
  KEY idx_v05_batch_score_contribution_family (profile_id, dt, scenario_name, score_family),
  KEY idx_v05_batch_score_contribution_metric (profile_id, dt, scenario_name, input_metric_scope, input_metric_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
