-- CASE-OBS-001 Phase2-B: Gap Measurement Layer
-- SQL role: persistence only. Python materializes direct measurement rows.

CREATE TABLE IF NOT EXISTS v05_obs_app_version_measurement_day (
  profile_id VARCHAR(128) NOT NULL,
  target_date DATE NOT NULL,
  scenario_name VARCHAR(128) NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT NOT NULL DEFAULT 0,
  app_platform VARCHAR(64) NOT NULL DEFAULT 'unknown',
  app_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  sdk_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  webserver_events BIGINT DEFAULT 0,
  wc_events BIGINT DEFAULT 0,
  canonical_events BIGINT DEFAULT 0,
  canonical_behavior_events BIGINT DEFAULT 0,
  webserver_uv BIGINT DEFAULT 0,
  wc_uv BIGINT DEFAULT 0,
  webserver_visit BIGINT DEFAULT 0,
  wc_visit BIGINT DEFAULT 0,
  webserver_pv BIGINT DEFAULT 0,
  wc_pv BIGINT DEFAULT 0,
  webserver_conversion BIGINT DEFAULT 0,
  wc_conversion BIGINT DEFAULT 0,
  missing_count BIGINT DEFAULT 0,
  missing_rate DOUBLE DEFAULT 0,
  uv_missing_rate DOUBLE DEFAULT 0,
  visit_missing_rate DOUBLE DEFAULT 0,
  pv_missing_rate DOUBLE DEFAULT 0,
  conversion_missing_rate DOUBLE DEFAULT 0,
  baseline_missing_rate DOUBLE DEFAULT NULL,
  gap_delta_from_baseline DOUBLE DEFAULT NULL,
  tagging_missing_flag TINYINT(1) DEFAULT 0,
  detail_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(detail_json)),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(profile_id,target_date,scenario_name,run_id,source_gen_run_id,app_platform,app_version,sdk_version),
  KEY idx_v05_obs_app_gap_rate (profile_id,target_date,missing_rate),
  KEY idx_v05_obs_app_sdk (profile_id,target_date,app_platform,sdk_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v05_obs_sdk_version_measurement_day (
  profile_id VARCHAR(128) NOT NULL,
  target_date DATE NOT NULL,
  scenario_name VARCHAR(128) NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT NOT NULL DEFAULT 0,
  app_platform VARCHAR(64) NOT NULL DEFAULT 'unknown',
  sdk_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  webserver_events BIGINT DEFAULT 0,
  wc_events BIGINT DEFAULT 0,
  webserver_uv BIGINT DEFAULT 0,
  wc_uv BIGINT DEFAULT 0,
  webserver_visit BIGINT DEFAULT 0,
  wc_visit BIGINT DEFAULT 0,
  webserver_pv BIGINT DEFAULT 0,
  wc_pv BIGINT DEFAULT 0,
  webserver_conversion BIGINT DEFAULT 0,
  wc_conversion BIGINT DEFAULT 0,
  missing_count BIGINT DEFAULT 0,
  missing_rate DOUBLE DEFAULT 0,
  uv_missing_rate DOUBLE DEFAULT 0,
  visit_missing_rate DOUBLE DEFAULT 0,
  pv_missing_rate DOUBLE DEFAULT 0,
  conversion_missing_rate DOUBLE DEFAULT 0,
  affected_app_versions INT DEFAULT 0,
  baseline_missing_rate DOUBLE DEFAULT NULL,
  gap_delta_from_baseline DOUBLE DEFAULT NULL,
  tagging_missing_flag TINYINT(1) DEFAULT 0,
  detail_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(detail_json)),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(profile_id,target_date,scenario_name,run_id,source_gen_run_id,app_platform,sdk_version),
  KEY idx_v05_obs_sdk_gap_rate (profile_id,target_date,missing_rate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v05_obs_url_gap_day (
  profile_id VARCHAR(128) NOT NULL,
  target_date DATE NOT NULL,
  scenario_name VARCHAR(128) NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT NOT NULL DEFAULT 0,
  app_platform VARCHAR(64) NOT NULL DEFAULT 'unknown',
  app_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  sdk_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  surface_path VARCHAR(191) NOT NULL DEFAULT 'unknown',
  webserver_events BIGINT DEFAULT 0,
  wc_events BIGINT DEFAULT 0,
  missing_count BIGINT DEFAULT 0,
  missing_rate DOUBLE DEFAULT 0,
  webserver_uv BIGINT DEFAULT 0,
  wc_uv BIGINT DEFAULT 0,
  uv_missing_rate DOUBLE DEFAULT 0,
  tagging_missing_flag TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(profile_id,target_date,scenario_name,run_id,source_gen_run_id,app_platform,app_version,sdk_version,surface_path),
  KEY idx_v05_obs_url_gap_rate (profile_id,target_date,missing_rate),
  KEY idx_v05_obs_url_surface (profile_id,target_date,surface_path)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v05_obs_client_gap_day (
  profile_id VARCHAR(128) NOT NULL,
  target_date DATE NOT NULL,
  scenario_name VARCHAR(128) NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT NOT NULL DEFAULT 0,
  app_platform VARCHAR(64) NOT NULL DEFAULT 'unknown',
  app_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  sdk_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  device_type VARCHAR(64) NOT NULL DEFAULT 'unknown',
  browser_family VARCHAR(64) NOT NULL DEFAULT 'unknown',
  os_family VARCHAR(64) NOT NULL DEFAULT 'unknown',
  webserver_events BIGINT DEFAULT 0,
  wc_events BIGINT DEFAULT 0,
  missing_count BIGINT DEFAULT 0,
  missing_rate DOUBLE DEFAULT 0,
  webserver_uv BIGINT DEFAULT 0,
  wc_uv BIGINT DEFAULT 0,
  uv_missing_rate DOUBLE DEFAULT 0,
  tagging_missing_flag TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(profile_id,target_date,scenario_name,run_id,source_gen_run_id,app_platform,app_version,sdk_version,device_type,browser_family,os_family),
  KEY idx_v05_obs_client_gap_rate (profile_id,target_date,missing_rate),
  KEY idx_v05_obs_client_platform (profile_id,target_date,app_platform,app_version,sdk_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v05_obs_metric_gap_day (
  profile_id VARCHAR(128) NOT NULL,
  target_date DATE NOT NULL,
  scenario_name VARCHAR(128) NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT NOT NULL DEFAULT 0,
  dimension_type VARCHAR(64) NOT NULL,
  dimension_value VARCHAR(191) NOT NULL,
  metric_name VARCHAR(64) NOT NULL,
  web_value DOUBLE DEFAULT 0,
  wc_value DOUBLE DEFAULT 0,
  missing_value DOUBLE DEFAULT 0,
  gap_rate DOUBLE DEFAULT 0,
  baseline_web_value DOUBLE DEFAULT NULL,
  baseline_wc_value DOUBLE DEFAULT NULL,
  baseline_gap_rate DOUBLE DEFAULT NULL,
  gap_delta_from_baseline DOUBLE DEFAULT NULL,
  severity VARCHAR(32) DEFAULT 'low',
  tagging_missing_flag TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(profile_id,target_date,scenario_name,run_id,source_gen_run_id,dimension_type,dimension_value,metric_name),
  KEY idx_v05_obs_metric_gap_rate (profile_id,target_date,metric_name,gap_rate),
  KEY idx_v05_obs_metric_dimension (profile_id,target_date,dimension_type,dimension_value)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CASE-OBS-001 Phase4-D: realistic scenario measurement extensions.
-- These are direct measurements only. Authority layers consume primitive scores,
-- not concrete app/sdk/url labels.
CREATE TABLE IF NOT EXISTS v05_obs_identity_gap_day (
  profile_id VARCHAR(128) NOT NULL,
  target_date DATE NOT NULL,
  scenario_name VARCHAR(128) NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT NOT NULL DEFAULT 0,
  app_platform VARCHAR(64) NOT NULL DEFAULT 'unknown',
  app_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  sdk_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  webserver_events BIGINT DEFAULT 0,
  wc_events BIGINT DEFAULT 0,
  webserver_uid_events BIGINT DEFAULT 0,
  wc_uid_events BIGINT DEFAULT 0,
  uid_missing_count BIGINT DEFAULT 0,
  uid_missing_rate DOUBLE DEFAULT 0,
  webserver_login_users BIGINT DEFAULT 0,
  wc_login_users BIGINT DEFAULT 0,
  login_user_gap_rate DOUBLE DEFAULT 0,
  identity_integrity_gap DOUBLE DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(profile_id,target_date,scenario_name,run_id,source_gen_run_id,app_platform,app_version,sdk_version),
  KEY idx_v05_obs_identity_gap (profile_id,target_date,identity_integrity_gap),
  KEY idx_v05_obs_identity_app (profile_id,target_date,app_platform,app_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v05_obs_url_semantic_gap_day (
  profile_id VARCHAR(128) NOT NULL,
  target_date DATE NOT NULL,
  scenario_name VARCHAR(128) NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT NOT NULL DEFAULT 0,
  app_platform VARCHAR(64) NOT NULL DEFAULT 'unknown',
  app_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  sdk_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
  surface_path VARCHAR(191) NOT NULL DEFAULT 'unknown',
  webserver_events BIGINT DEFAULT 0,
  wc_events BIGINT DEFAULT 0,
  under_count BIGINT DEFAULT 0,
  over_count BIGINT DEFAULT 0,
  under_rate DOUBLE DEFAULT 0,
  over_rate DOUBLE DEFAULT 0,
  distribution_shift_score DOUBLE DEFAULT 0,
  url_collapse_flag TINYINT(1) DEFAULT 0,
  shifted_direction VARCHAR(32) DEFAULT 'none',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(profile_id,target_date,scenario_name,run_id,source_gen_run_id,app_platform,app_version,sdk_version,surface_path),
  KEY idx_v05_obs_url_semantic_shift (profile_id,target_date,distribution_shift_score),
  KEY idx_v05_obs_url_semantic_sdk (profile_id,target_date,app_platform,sdk_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v05_obs_business_kpi_gap_day (
  profile_id VARCHAR(128) NOT NULL,
  target_date DATE NOT NULL,
  scenario_name VARCHAR(128) NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT NOT NULL DEFAULT 0,
  scope_type VARCHAR(64) NOT NULL DEFAULT 'all',
  scope_value VARCHAR(191) NOT NULL DEFAULT 'all',
  pv_gap_rate DOUBLE DEFAULT 0,
  uv_gap_rate DOUBLE DEFAULT 0,
  visit_gap_rate DOUBLE DEFAULT 0,
  conversion_gap_rate DOUBLE DEFAULT 0,
  purchase_event_gap_rate DOUBLE DEFAULT 0,
  revenue_proxy_gap_rate DOUBLE DEFAULT 0,
  traffic_preservation_score DOUBLE DEFAULT 0,
  business_kpi_distortion_score DOUBLE DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY(profile_id,target_date,scenario_name,run_id,source_gen_run_id,scope_type,scope_value),
  KEY idx_v05_obs_business_kpi_gap (profile_id,target_date,business_kpi_distortion_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
