-- CASE-OBS-001 Phase2-C1 Baseline Science Foundation
-- OBS-only baseline layer. Does not modify v0.5 core baseline reference tables.

CREATE TABLE IF NOT EXISTS v05_obs_baseline_reference_day (
  profile_id VARCHAR(64) NOT NULL,
  target_date DATE NOT NULL,
  baseline_window VARCHAR(32) NOT NULL,
  baseline_scenario_name VARCHAR(128) NOT NULL DEFAULT 'baseline',
  baseline_type VARCHAR(64) NOT NULL,
  baseline_start_date DATE NULL,
  baseline_end_date DATE NULL,
  sample_days INT NOT NULL DEFAULT 0,
  is_usable TINYINT NOT NULL DEFAULT 0,
  quality_score DECIMAL(10,6) NOT NULL DEFAULT 0,
  fallback_policy VARCHAR(128) NULL,
  source_table VARCHAR(128) NULL,
  detail_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (profile_id, target_date, baseline_window, baseline_scenario_name, baseline_type),
  KEY idx_v05_obs_base_ref_usable (profile_id, target_date, is_usable, quality_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v05_obs_baseline_feature_snapshot_day (
  profile_id VARCHAR(64) NOT NULL,
  target_date DATE NOT NULL,
  scenario_name VARCHAR(128) NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT NOT NULL DEFAULT 0,
  dimension_type VARCHAR(64) NOT NULL,
  dimension_key VARCHAR(191) NOT NULL,
  metric_name VARCHAR(64) NOT NULL,
  metric_value DECIMAL(18,8) NULL,
  webserver_value DECIMAL(18,4) NULL,
  wc_value DECIMAL(18,4) NULL,
  missing_value DECIMAL(18,4) NULL,
  missing_rate DECIMAL(18,8) NULL,
  source_table VARCHAR(128) NOT NULL,
  source_dimension_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (profile_id, target_date, scenario_name, run_id, source_gen_run_id, dimension_type, dimension_key, metric_name, source_table),
  KEY idx_v05_obs_base_feat_lookup (profile_id, target_date, scenario_name, dimension_type, metric_name),
  KEY idx_v05_obs_base_feat_dim (profile_id, dimension_type, dimension_key, metric_name, target_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v05_obs_baseline_stat_profile_day (
  profile_id VARCHAR(64) NOT NULL,
  target_date DATE NOT NULL,
  baseline_window VARCHAR(32) NOT NULL,
  baseline_scenario_name VARCHAR(128) NOT NULL DEFAULT 'baseline',
  baseline_type VARCHAR(64) NOT NULL,
  dimension_type VARCHAR(64) NOT NULL,
  dimension_key VARCHAR(191) NOT NULL,
  metric_name VARCHAR(64) NOT NULL,
  sample_days INT NOT NULL DEFAULT 0,
  mean_value DECIMAL(18,8) NULL,
  sd_value DECIMAL(18,8) NULL,
  median_value DECIMAL(18,8) NULL,
  p75_value DECIMAL(18,8) NULL,
  p90_value DECIMAL(18,8) NULL,
  p95_value DECIMAL(18,8) NULL,
  p99_value DECIMAL(18,8) NULL,
  min_value DECIMAL(18,8) NULL,
  max_value DECIMAL(18,8) NULL,
  lower_control_limit DECIMAL(18,8) NULL,
  upper_control_limit DECIMAL(18,8) NULL,
  quality_score DECIMAL(10,6) NOT NULL DEFAULT 0,
  baseline_status VARCHAR(64) NOT NULL DEFAULT 'unknown',
  source_table VARCHAR(128) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (profile_id, target_date, baseline_window, baseline_scenario_name, baseline_type, dimension_type, dimension_key, metric_name),
  KEY idx_v05_obs_base_stat_lookup (profile_id, target_date, dimension_type, metric_name, baseline_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS v05_obs_baseline_compare_day (
  profile_id VARCHAR(64) NOT NULL,
  target_date DATE NOT NULL,
  scenario_name VARCHAR(128) NOT NULL,
  run_id BIGINT NOT NULL DEFAULT 0,
  source_gen_run_id BIGINT NOT NULL DEFAULT 0,
  baseline_window VARCHAR(32) NOT NULL,
  baseline_scenario_name VARCHAR(128) NOT NULL DEFAULT 'baseline',
  selected_baseline_type VARCHAR(64) NOT NULL,
  dimension_type VARCHAR(64) NOT NULL,
  dimension_key VARCHAR(191) NOT NULL,
  metric_name VARCHAR(64) NOT NULL,
  current_value DECIMAL(18,8) NULL,
  baseline_mean DECIMAL(18,8) NULL,
  baseline_sd DECIMAL(18,8) NULL,
  baseline_p95 DECIMAL(18,8) NULL,
  baseline_upper_control_limit DECIMAL(18,8) NULL,
  baseline_delta DECIMAL(18,8) NULL,
  z_score DECIMAL(18,8) NULL,
  percentile_band VARCHAR(32) NULL,
  control_limit_breach TINYINT NOT NULL DEFAULT 0,
  baseline_quality_score DECIMAL(10,6) NOT NULL DEFAULT 0,
  sample_days INT NOT NULL DEFAULT 0,
  severity VARCHAR(32) NOT NULL DEFAULT 'normal',
  baseline_status VARCHAR(64) NOT NULL DEFAULT 'unknown',
  detail_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (profile_id, target_date, scenario_name, run_id, source_gen_run_id, baseline_window, dimension_type, dimension_key, metric_name),
  KEY idx_v05_obs_base_cmp_sev (profile_id, target_date, scenario_name, severity),
  KEY idx_v05_obs_base_cmp_dim (profile_id, dimension_type, metric_name, severity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
